### POST request to example server
POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBib2IuY29tIiwiZXhwIjoxNzcyNDAyOTMzLCJ1c2VySWQiOjF9.OweDg2zFihb7VC71ow6qRtgcrFdvJG60dN-PhmTA8sU

{
  "name": "Testing Event",
  "description": "A test event",
  "location": "interface city 2",
  "date_time": "2026-02-23T15:30:00.000Z"
}
###