### POST request to example server
POST http://localhost:8080/events
content-type: application/json

{
  "name": "Test Interfaces Event",
  "description": "A test event with interface stuff",
  "location": "interface city",
  "dateTime": "2026-02-23T15:30:00.000Z",
  "userID": 1
}
###