### PUT request to example server
PUT http://localhost:8080/events/343d6e51-8ca7-4393-a5e0-2e22d21d44c1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBib2IuY29tIiwiZXhwIjoxNzcyNDAyOTMzLCJ1c2VySWQiOjF9.OweDg2zFihb7VC71ow6qRtgcrFdvJG60dN-PhmTA8sU

{
  "name": "updated event",
  "description": "updated the event",
  "location": "Atlanta",
  "date_time": "2026-02-23T15:30:00.000Z"
}
###