### POST request to example server
POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBib2IuY29tIiwiZXhwIjoxNzcyMjMyNDc2LCJ1c2VySWQiOiJlNmJhMjg0Ni00NTEwLTQ4YjktYmQ2Yi0zNzg2ZmJmMzI3YWMifQ._dyOdMGzvGceB8EjxIG8Jwaue97aBcSk9vp-9xca4Uk

{
  "name": "Test Interfaces Event",
  "description": "A test event with interface stuff",
  "location": "interface city",
  "dateTime": "2026-02-23T15:30:00.000Z"
}
###