### POST request to example server
POST http://localhost:8080/users
content-type: application/json

{
  "email": "bob@bob2.com",
  "password": "Password123!",
  "firstName": "Bob",
  "lastName": "Bobson"
}
###